/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BasicErrorControllerApi
 */
@Ignore
public class BasicErrorControllerApiTest {

    private final BasicErrorControllerApi api = new BasicErrorControllerApi();

    
    /**
     * error
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void errorUsingDELETETest() throws ApiException {
        Map<String, Object> response = api.errorUsingDELETE();

        // TODO: test validations
    }
    
    /**
     * error
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void errorUsingGETTest() throws ApiException {
        Map<String, Object> response = api.errorUsingGET();

        // TODO: test validations
    }
    
    /**
     * error
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void errorUsingHEADTest() throws ApiException {
        Map<String, Object> response = api.errorUsingHEAD();

        // TODO: test validations
    }
    
    /**
     * error
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void errorUsingOPTIONSTest() throws ApiException {
        Map<String, Object> response = api.errorUsingOPTIONS();

        // TODO: test validations
    }
    
    /**
     * error
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void errorUsingPATCHTest() throws ApiException {
        Map<String, Object> response = api.errorUsingPATCH();

        // TODO: test validations
    }
    
    /**
     * error
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void errorUsingPOSTTest() throws ApiException {
        Map<String, Object> response = api.errorUsingPOST();

        // TODO: test validations
    }
    
    /**
     * error
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void errorUsingPUTTest() throws ApiException {
        Map<String, Object> response = api.errorUsingPUT();

        // TODO: test validations
    }
    
}
