/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.RepresentationModelobject;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProfileControllerApi
 */
@Ignore
public class ProfileControllerApiTest {

    private final ProfileControllerApi api = new ProfileControllerApi();

    
    /**
     * listAllFormsOfMetadata
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listAllFormsOfMetadataUsingGETTest() throws ApiException {
        RepresentationModelobject response = api.listAllFormsOfMetadataUsingGET();

        // TODO: test validations
    }
    
    /**
     * profileOptions
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void profileOptionsUsingOPTIONSTest() throws ApiException {
        Object response = api.profileOptionsUsingOPTIONS();

        // TODO: test validations
    }
    
}
