/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.CollectionModelRegistration;
import io.swagger.client.model.EntityModelRegistration;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TaxEntityApi
 */
@Ignore
public class TaxEntityApiTest {

    private final TaxEntityApi api = new TaxEntityApi();

    
    /**
     * taxTax
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void taxTaxUsingDELETETest() throws ApiException {
        Integer id = null;
        String registrationId = null;
        api.taxTaxUsingDELETE(id, registrationId);

        // TODO: test validations
    }
    
    /**
     * taxTax
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void taxTaxUsingDELETE1Test() throws ApiException {
        Integer id = null;
        api.taxTaxUsingDELETE1(id);

        // TODO: test validations
    }
    
    /**
     * taxTax
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void taxTaxUsingGETTest() throws ApiException {
        Integer id = null;
        CollectionModelRegistration response = api.taxTaxUsingGET(id);

        // TODO: test validations
    }
    
    /**
     * taxTax
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void taxTaxUsingGET1Test() throws ApiException {
        Integer id = null;
        String registrationId = null;
        EntityModelRegistration response = api.taxTaxUsingGET1(id, registrationId);

        // TODO: test validations
    }
    
    /**
     * taxTax
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void taxTaxUsingPATCHTest() throws ApiException {
        List<String> body = null;
        Integer id = null;
        CollectionModelRegistration response = api.taxTaxUsingPATCH(body, id);

        // TODO: test validations
    }
    
    /**
     * taxTax
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void taxTaxUsingPOSTTest() throws ApiException {
        List<String> body = null;
        Integer id = null;
        CollectionModelRegistration response = api.taxTaxUsingPOST(body, id);

        // TODO: test validations
    }
    
    /**
     * taxTax
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void taxTaxUsingPUTTest() throws ApiException {
        List<String> body = null;
        Integer id = null;
        CollectionModelRegistration response = api.taxTaxUsingPUT(body, id);

        // TODO: test validations
    }
    
}
