/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Car;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Customer
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-05-24T14:15:56.866+01:00")
public class Customer {
  @SerializedName("address")
  private String address = null;

  @SerializedName("customer")
  private List<Car> customer = null;

  @SerializedName("customerid")
  private Integer customerid = null;

  @SerializedName("fname")
  private String fname = null;

  @SerializedName("postcode")
  private String postcode = null;

  @SerializedName("sname")
  private String sname = null;

  public Customer address(String address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @ApiModelProperty(value = "")
  public String getAddress() {
    return address;
  }

  public void setAddress(String address) {
    this.address = address;
  }

  public Customer customer(List<Car> customer) {
    this.customer = customer;
    return this;
  }

  public Customer addCustomerItem(Car customerItem) {
    if (this.customer == null) {
      this.customer = new ArrayList<Car>();
    }
    this.customer.add(customerItem);
    return this;
  }

   /**
   * Get customer
   * @return customer
  **/
  @ApiModelProperty(value = "")
  public List<Car> getCustomer() {
    return customer;
  }

  public void setCustomer(List<Car> customer) {
    this.customer = customer;
  }

  public Customer customerid(Integer customerid) {
    this.customerid = customerid;
    return this;
  }

   /**
   * Get customerid
   * @return customerid
  **/
  @ApiModelProperty(value = "")
  public Integer getCustomerid() {
    return customerid;
  }

  public void setCustomerid(Integer customerid) {
    this.customerid = customerid;
  }

  public Customer fname(String fname) {
    this.fname = fname;
    return this;
  }

   /**
   * Get fname
   * @return fname
  **/
  @ApiModelProperty(value = "")
  public String getFname() {
    return fname;
  }

  public void setFname(String fname) {
    this.fname = fname;
  }

  public Customer postcode(String postcode) {
    this.postcode = postcode;
    return this;
  }

   /**
   * Get postcode
   * @return postcode
  **/
  @ApiModelProperty(value = "")
  public String getPostcode() {
    return postcode;
  }

  public void setPostcode(String postcode) {
    this.postcode = postcode;
  }

  public Customer sname(String sname) {
    this.sname = sname;
    return this;
  }

   /**
   * Get sname
   * @return sname
  **/
  @ApiModelProperty(value = "")
  public String getSname() {
    return sname;
  }

  public void setSname(String sname) {
    this.sname = sname;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Customer customer = (Customer) o;
    return Objects.equals(this.address, customer.address) &&
        Objects.equals(this.customer, customer.customer) &&
        Objects.equals(this.customerid, customer.customerid) &&
        Objects.equals(this.fname, customer.fname) &&
        Objects.equals(this.postcode, customer.postcode) &&
        Objects.equals(this.sname, customer.sname);
  }

  @Override
  public int hashCode() {
    return Objects.hash(address, customer, customerid, fname, postcode, sname);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Customer {\n");
    
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    customer: ").append(toIndentedString(customer)).append("\n");
    sb.append("    customerid: ").append(toIndentedString(customerid)).append("\n");
    sb.append("    fname: ").append(toIndentedString(fname)).append("\n");
    sb.append("    postcode: ").append(toIndentedString(postcode)).append("\n");
    sb.append("    sname: ").append(toIndentedString(sname)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

