/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Registration;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Embedded collection of Registration
 */
@ApiModel(description = "Embedded collection of Registration")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-05-24T14:15:56.866+01:00")
public class EmbeddedCollectionRegistration {
  @SerializedName("registration")
  private List<Registration> registration = new ArrayList<Registration>();

  public EmbeddedCollectionRegistration registration(List<Registration> registration) {
    this.registration = registration;
    return this;
  }

  public EmbeddedCollectionRegistration addRegistrationItem(Registration registrationItem) {
    this.registration.add(registrationItem);
    return this;
  }

   /**
   * Resource collection
   * @return registration
  **/
  @ApiModelProperty(required = true, value = "Resource collection")
  public List<Registration> getRegistration() {
    return registration;
  }

  public void setRegistration(List<Registration> registration) {
    this.registration = registration;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmbeddedCollectionRegistration embeddedCollectionRegistration = (EmbeddedCollectionRegistration) o;
    return Objects.equals(this.registration, embeddedCollectionRegistration.registration);
  }

  @Override
  public int hashCode() {
    return Objects.hash(registration);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmbeddedCollectionRegistration {\n");
    
    sb.append("    registration: ").append(toIndentedString(registration)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

