/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Tax;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Embedded collection of Tax
 */
@ApiModel(description = "Embedded collection of Tax")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-05-24T14:15:56.866+01:00")
public class EmbeddedCollectionTax {
  @SerializedName("tax")
  private List<Tax> tax = new ArrayList<Tax>();

  public EmbeddedCollectionTax tax(List<Tax> tax) {
    this.tax = tax;
    return this;
  }

  public EmbeddedCollectionTax addTaxItem(Tax taxItem) {
    this.tax.add(taxItem);
    return this;
  }

   /**
   * Resource collection
   * @return tax
  **/
  @ApiModelProperty(required = true, value = "Resource collection")
  public List<Tax> getTax() {
    return tax;
  }

  public void setTax(List<Tax> tax) {
    this.tax = tax;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmbeddedCollectionTax embeddedCollectionTax = (EmbeddedCollectionTax) o;
    return Objects.equals(this.tax, embeddedCollectionTax.tax);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tax);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmbeddedCollectionTax {\n");
    
    sb.append("    tax: ").append(toIndentedString(tax)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

